### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by natdm** [mislav/gh-branch#10]
https://hacktoberfest.digitalocean.com/faq

> You can politely request the maintainer of the project you contributed to, to tag your contribution with the label **hacktoberfest-accepted** . Or, add the 'hacktoberfest' topic to the repository to opt the project into Hacktoberfest.
> 
> Any pull request with the **hacktoberfest-accepted** label, submitted to any public GitHub/GitLab repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.

Any way we can add the topic?

**Comment by mislav** [comment]
Sorry, I've missed this! However, I didn't have time to engage with this in October, so this repository wouldn't have been a good fit for Hacktoberfest.
