### ISSUE TITLE
Missing branches

### ISSUE THREAD

**Issue by pmareke** [mislav/gh-branch#4]
First of all, THANKS for your extension!

I've installed it today and some branches didn't appear and I think that it's because of the `branch_info` method

```shell
branch_info() {
  git for-each-ref 'refs/heads/*' --format='%(refname:short)%09%(committerdate:unix)%09%(committerdate:relative)%09%(HEAD)'
}'
```

The problem seems to be the `refs/heads/*'` instead of `refs/heads/**`.

I'll show some examples:
![image](https://user-images.githubusercontent.com/3502075/130674083-531040f0-6b1e-4f2f-98c3-7efcc6c22109.png)

Thanks in advanced and if you need anything just tell me!

PD: If you think that what I'm telling you is correct I will have not problem in open a PR!

**Comment by mislav** [comment]
Great find! Thank you 🙇

**Comment by pmareke** [comment]
Thanks to you, now it works perfectly!
