### ISSUE TITLE
Is it possible to list remote branches as well?

### ISSUE THREAD

**Issue by tnorthcutt** [mislav/gh-branch#7]
Thanks for this extension! I've already found it very useful.

I'm curious: would it be possible to modify this to also include remote branches? I would be more than happy to work on adding that, but I'm honestly not entirely sure where to start.

**Comment by matt-bartel** [comment]
I got this working on [my fork](https://github.com/mislav/gh-branch/compare/main...matt-bartel:main). Let me know if you'd like a PR.
